server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/workinwow?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 2422056087@qq.com
    password: qccdxclryvkndijg
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
